name: evaluate_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # 3.8
  - pandas=1.5.3 # 1.2.3
  - numpy=1.23.5
  - pip=23.2.1 # 20.3.3
  - scikit-learn=1.3.0 # 0.24.2
  - matplotlib=3.7.2 # 3.2.2
  - plotly=5.10.0 # 4.4.1
  - pillow=9.3.0 # 8.1.2
  - mlflow=2.2.0 # 1.26.0
  - boto3=1.28.14 # 1.23.5
