name: evaluate_model
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.2.3
  - numpy=1.16.5
  - pip=20.3.3
  - scikit-learn=0.24.2
  - matplotlib=3.2.2
  - plotly=4.4.1
  - pillow=8.1.2
  - mlflow=1.26.0
  - boto3=1.23.5
