name: preprocess_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10 # 3.8
  - pandas=1.5.3 # 1.2.3
  - numpy=1.23.5
  - pip=23.2.1 # 20.3.3
  - pyarrow=11.0.0 # 2.0
  - mlflow=2.2.0 # 1.26.0
  - boto3=1.28.14 # 1.23.5