name: pipeline-ml-mlflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # manejo de datos
  - pandas=1.5.3
  - numpy
  # gráficos
  - matplotlib
  - seaborn
  # machine learning
  - jupyter
  - scikit-learn=1.3.0
  - hyperopt
  # feature engineering
  - ydata-profiling
  - feature_engine
  - imbalanced-learn
  # utils
  - ipykernel
  - ipython
  - virtualenv==20.17.1
  - requests
  - pip
  # mlflow
  - mlflow=2.2.0
  - hydra-core=1.3.2
  - pip:
      - hydra-joblib-launcher==1.2.0