name: genre-classification

on: push
  branches: dev

jobs:
  build:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    #container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    container: alangrosso/cml-conda:latest
    
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.ML_PIPELINE_GITHUB_TOKEN }}
        run: |
          pip3 install mlflow==2.2.0
          mlflow run 04-pipeline-ml-ci-cd/.

          echo "## Model metrics" > report.md
          cat ./evaluate/metrics.txt >> report.md

          echo "## Confusion Matrix Test Dataset" >> report.md

          cml-publish ./evaluate/img/confusion_matrix.png --md >> report.md
          #cml-publish residuals.png --md >> report.md

          cml-send-comment report.md