name: genre-classification

on: 
  push:
    branches: 
      - dev

jobs:
  train-and-report: # nombre del job
    runs-on: [ubuntu-latest]
    container: alangrosso/cml-conda:latest
    
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3
      
      - name: Ejecutar MLflow cml-run
        run: |
          # Configurar la variable de entorno para mostrar errores completos de Hydra
          export HYDRA_FULL_ERROR=1
          
          # Actualizar e instalar
          pip3 install --upgrade protobuf==3.20.0
          pip3 install mlflow==1.26.0

          # Ejecutar pipeline
          mlflow run 04-pipeline-ml-ci-cd/.
          
          # Generar reporte en Markdown
          echo "## Model metrics" > report.md
          cat 04-pipeline-ml-ci-cd/evaluate/metrics.txt >> report.md
          echo "## Confusion Matrix Test Dataset" >> report.md
          echo "![](04-pipeline-ml-ci-cd/evaluate/img/confusion_matrix.png)" >> report.md

          # Enviar el informe
          cml comment create report.md
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}