name: genre-classification

on: 
  push:
    branches: 
      - dev

jobs:
  build: # nombre del job
    runs-on: [ubuntu-latest]
    container: alangrosso/cml-conda:latest
    
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v2
      
      - name: Setup NodeJS 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: cml-run
        env:
          repo_token: ${{ secrets.ML_PIPELINE_GITHUB_TOKEN }}
        run: |
          export HYDRA_FULL_ERROR=1
          pip3 install mlflow==2.2.0
          mlflow run 04-pipeline-ml-ci-cd/.

          echo "## Model metrics" > report.md
          cat ./evaluate/metrics.txt >> report.md

          echo "## Confusion Matrix Test Dataset" >> report.md

          cml-publish ./evaluate/img/confusion_matrix.png --md >> report.md
          #cml-publish residuals.png --md >> report.md

          cml-send-comment report.md